version: 2

models:
  # Core Schema
  - name: coins
    description: "core.coins table"
    meta:
      schema: core  # Documenting the dataset (core)
    columns:
      - name: coin_id
        description: "Unique ID for each coin"
        data_tests:
          - not_null
          - unique
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - chain_id
            - address

  - name: coin_facts_metadata
    description: "aggregated metadata from all sources"
    meta:
      schema: core  # Documenting the dataset (core)
    columns:
      - name: coin_id
        description: "Unique ID for each coin"
        data_tests:
          - not_null
          - unique

  - name: coin_facts_coingecko
    description: "metadata from coingecko only"
    meta:
      schema: core  # Documenting the dataset (core)
    columns:
      - name: coin_id
        description: "Unique ID for each coin"
        data_tests:
          - not_null
          - unique
      - name: coingecko_id
        data_tests:
          - not_null
          - unique

  - name: coin_market_data
    description: "market data aggregated from all sources"
    meta:
      schema: core
    columns:
      - name: date
        description: "The date of the market data"
      - name: coin_id
        description: "coin_id"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - coin_id

  # ETL Pipelines Schema
  - name: coin_geckoterminal_metadata
    description: "Metadata for Geckoterminal coins"
    meta:
      schema: etl_pipelines  # Documenting the dataset (etl_pipelines)
    columns:
      - name: geckoterminal_id
        description: "ID of geckoterminal coin"
        data_tests:
          - not_null
          - unique

  - name: coin_market_data_coingecko
    description: "Coingecko market data"
    meta:
      schema: etl_pipelines
    columns:
      - name: date
        description: "The date of the market data"
        data_tests:
          - not_null
      - name: coingecko_id
        description: "The Coingecko ID of the coin"
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - coingecko_id