
version: 2

models:
  - name: core_coins
    description: "core.coins table"
    columns:
      - name: coin_id
        description: "Unique ID for each coin"
        data_tests:
          - not_null
          - unique
