version: 2

models:
  # Core Schema
  - name: coins
    description: "core.coins table"
    meta:
      schema: core  # Documenting the dataset (core)
    columns:
      - name: coin_id
        description: "Unique ID for each coin"
        data_tests:
          - not_null
          - unique
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - chain_id
            - address

  - name: coin_facts_metadata
    description: "aggregated metadata from all sources"
    meta:
      schema: core  # Documenting the dataset (core)
    columns:
      - name: coin_id
        description: "Unique ID for each coin"
        data_tests:
          - not_null
          - unique
      - name: coingecko_id
        description: "Coingecko's unique ID"
        data_tests:
          - unique
      - name: geckoterminal_id
        description: "Geckoterminal's unique ID"
        data_tests:
          - unique

  - name: coin_facts_coingecko
    description: "metadata from coingecko only"
    meta:
      schema: core  # Documenting the dataset (core)
    columns:
      - name: coin_id
        description: "Unique ID for each coin"
        data_tests:
          - not_null
          - unique
      - name: coingecko_id
        data_tests:
          - not_null
          - unique

  - name: coin_market_data
    description: "market data aggregated from all sources"
    meta:
      schema: core
    columns:
      - name: date
        description: "The date of the market data"
        data_tests:
          - not_null
      - name: coin_id
        description: "coin_id"
        data_tests:
          - not_null
      - name: price
        description: "price"
        data_tests:
        - not_null
      - name: volume
        description: "trading volume"
        data_tests:
        - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - coin_id

  - name: coin_wallet_transfers
    description: "token-demoninated wallet activity"
    meta:
      schema: core
    columns:
      - name: date
        description: "The date of the transfers"
        data_tests:
          - not_null
      - name: coin_id
        description: "coin_id"
        data_tests:
          - not_null
      - name: wallet_address
        description: "wallet address on the blockchain of the coin_id"
        data_tests:
          - not_null
      - name: net_transfers
        description: "the net amount transferred that day"
        data_tests:
        - not_null
      - name: balance
        description: "the wallet's balance of the coin_id"
        data_tests:
        - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - coin_id
            - wallet_address

  - name: coin_wallet_profits
    description: "usd-demoninated wallet activity"
    meta:
      schema: core
    columns:
      - name: date
        description: "The date of the transfers"
        data_tests:
          - not_null
      - name: coin_id
        description: "coin_id"
        data_tests:
          - not_null
      - name: wallet_address
        description: "wallet address on the blockchain of the coin_id"
        data_tests:
          - not_null
      - name: usd_net_transfers
        description: "the net amount transferred that day"
        data_tests:
        - not_null
      - name: usd_balance
        description: "the wallet's balance of the coin_id"
        data_tests:
        - not_null
      - name: usd_inflows_cumulative
        description: "the wallet's balance of the coin_id"
        data_tests:
        - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - coin_id
            - wallet_address


  # ETL Pipelines Schema
  - name: coin_geckoterminal_metadata
    description: "Metadata for Geckoterminal coins"
    meta:
      schema: etl_pipelines  # Documenting the dataset (etl_pipelines)
    columns:
      - name: geckoterminal_id
        description: "ID of geckoterminal coin"
        data_tests:
          - not_null
          - unique

  - name: coin_market_data_geckoterminal
    description: "Geckoterminal market data"
    meta:
      schema: etl_pipelines
    columns:
      - name: date
        description: "The date of the market data"
        data_tests:
          - not_null
      - name: geckoterminal_id
        description: "Geckoterminal's coin id per their API"
        data_tests:
          - not_null
      - name: close
        description: "daily closing price"
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - geckoterminal_id

  - name: coin_coingecko_metadata
    description: "Metadata for Coingecko coins"
    meta:
      schema: etl_pipelines  # Documenting the dataset (etl_pipelines)
    columns:
      - name: coingecko_id
        description: "coingecko_id"
        data_tests:
          - not_null
          - unique

  - name: coin_market_data_coingecko
    description: "Coingecko market data"
    meta:
      schema: etl_pipelines
    columns:
      - name: date
        description: "The date of the market data"
        data_tests:
          - not_null
      - name: coingecko_id
        description: "The Coingecko ID of the coin"
        data_tests:
          - not_null
      - name: price
        description: "daily price"
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - coingecko_id

  - name: coin_wallet_net_transfers
    description: "daily transfer data from dune"
    meta:
      schema: etl_pipelines
    columns:
      - name: date
        description: "transfer date"
        data_tests:
          - not_null
      - name: chain_text_source
        description: "dunesql blockchain alias"
        data_tests:
          - not_null
      - name: token_address
        description: "token address"
        data_tests:
          - not_null
      - name: wallet_address
        description: "wallet address"
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - chain_text_source
            - token_address
            - wallet_address

  - name: ethereum_net_transfers
    description: "daily transfer data from the public ethereum_transfers table"
    meta:
      schema: etl_pipelines
    columns:
      - name: date
        description: "transfer date"
        data_tests:
          - not_null
      - name: token_address
        description: "token address"
        data_tests:
          - not_null
      - name: wallet_address
        description: "wallet address"
        data_tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - token_address
            - wallet_address
