name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
    paths:
      - 

env:
  PROJECT: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Google Cloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        # Add your deployment commands here, e.g., deploying to App Engine
        gcloud app deploy app.yaml
