name: Deploy to Google Cloud
# from https://github.com/google-github-actions/deploy-cloud-functions

on:
  push:
    branches:
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'github-actions-deployer@western-verve-411004.iam.gserviceaccount.com'


    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v2'
      with:
        name: 'freshen_coin_wallet_net_transfers'
        runtime: 'python311'
        region: 'us-west1'

    - name: Deploy to Google Cloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        # Add your deployment commands here, e.g., deploying to App Engine
        gcloud app deploy app.yaml