name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# on: 
#   push:
#     paths:
#       - github_actions_poc/**
on: [push]
jobs:
  github-poc:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
  
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'western-verve-411004'
          workload_identity_provider: 'projects/954736581165/locations/global/workloadIdentityPools/github-actions/providers/github'
  
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 10
        with:
          name: 'github_actions_proof_of_concept '
          runtime: 'python311'